### ISSUE TITLE
What happend this ?

### ISSUE THREAD

**Issue by merakinoya** [benedmunds/CodeIgniter-Standard-Project#7]
A PHP Error was encountered
Severity: Notice
Message: Only variable references should be returned by reference
Filename: core/Common.php
Line Number: 257

A PHP Error was encountered
Severity: Notice
Message: Only variables should be assigned by reference
Filename: core/Loader.php
Line Number: 150

Fatal error: Uncaught Error: Call to undefined function mysql_pconnect() in C:\xampp\xampp\htdocs\CodeIgniter-Standard-Project-master\system\database\drivers\mysql\mysql_driver.php:91 Stack trace: #0 C:\xampp\xampp\htdocs\CodeIgniter-Standard-Project-master\system\database\DB_driver.php(115): CI_DB_mysql_driver->db_pconnect() #1 C:\xampp\xampp\htdocs\CodeIgniter-Standard-Project-master\system\database\DB.php(148): CI_DB_driver->initialize() #2 C:\xampp\xampp\htdocs\CodeIgniter-Standard-Project-master\system\core\Loader.php(346): DB(Array, NULL) #3 C:\xampp\xampp\htdocs\CodeIgniter-Standard-Project-master\system\core\Loader.php(1171): CI_Loader->database() #4 C:\xampp\xampp\htdocs\CodeIgniter-Standard-Project-master\system\core\Loader.php(152): CI_Loader->_ci_autoloader() #5 C:\xampp\xampp\htdocs\CodeIgniter-Standard-Project-master\system\core\Controller.php(51): CI_Loader->initialize() #6 C:\xampp\xampp\htdocs\CodeIgniter-Standard-Project-master\application\core\MY_Controller.php(23): CI_Controller->__construct() #7 C:\xa in C:\xampp\xampp\htdocs\CodeIgniter-Standard-Project-master\system\database\drivers\mysql\mysql_driver.php on line 91

![problem](https://user-images.githubusercontent.com/19262798/37944533-2b149690-31a6-11e8-9464-86336001771a.PNG)

**Comment by benedmunds** [comment]
I think you need to upgrade your version of CodeIgniter.  What version PHP and CI are you on?

**Comment by merakinoya** [comment]
my php version is 5,4 and CI version from this project, because I use this project directly

So what version is needed for php and ci?

**Comment by benedmunds** [comment]
Yea I really need to remove CI from this project, it was just meant to be an example.  The CI here is still on 2.1.0 which I think needed PHP 5.3 or so.

This project itself should work fine with a newer version of PHP, you'll just need to upgrade the CI.  Or you could try it as is with PHP <= 5.3
